### ISSUE TITLE
Update Azure VMs / Update Node Pool on AKS Cluster

### ISSUE THREAD

**Issue by LazuLitee** [zskarte/zskarte-server#48]
- [x] Upgrade Kubernetes Cluster to Latest Stable with Patch
- [x] Choose other VM Size for Cluster

**Comment by SwitzerChees** [comment]
No need for a bigger VM at the moment

- AVG CPU Load: 10 - 20%
- AVG Memory Usage: 70%

**Comment by Lucamuh** [comment]
Close issue due to no need
